# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - tensorflow==*=*cuda112*
 - pytorch==*=*cuda112*
 - torchgeo
 - jax=0.3.0
 - jaxlib=0.1.75