# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - pytorch>=1.12.0=*cuda112*
 - torchvision>=*=*cuda112*
 - torchgeo
